#!MC 1120
# Created by Tecplot 360 build 11.3.29.563
$!EXPORTSETUP EXPORTFORMAT = EPS
$!PRINTSETUP PALETTE = COLOR	# comment this line out if GRAYSCALE is needed
$!EXPORTSETUP IMAGEWIDTH = 1275
$!PRINTSETUP PRECISION = 8
$!EXPORTSETUP EPSPREVIEWIMAGE{IMAGETYPE = EPSIV2}
$!EXPORTSETUP EXPORTFNAME = 'temp.eps'
$!EXPORT 
  EXPORTREGION = ALLFRAMES